[package]
name = "secretpng"
version = "0.1.1"
authors = ["gabrielvictorcf <gabrielvcf@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
clap = "3.0.0-beta.2"
